// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfJpYUIcqH_QvryzJH1Rbsg3iAY0zW85Q',
    appId: '1:714082287468:web:4093c2a779d3b77757bd49',
    messagingSenderId: '714082287468',
    projectId: 'jewel-assist-e3d9c',
    authDomain: 'jewel-assist-e3d9c.firebaseapp.com',
    storageBucket: 'jewel-assist-e3d9c.appspot.com',
    measurementId: 'G-YWBWLC0EVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnpTtGGPRtOvE5_lLGB4JS7q31KiWThx0',
    appId: '1:714082287468:android:2221dadea6946cb157bd49',
    messagingSenderId: '714082287468',
    projectId: 'jewel-assist-e3d9c',
    storageBucket: 'jewel-assist-e3d9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfdeHATG8dxuCG7qTulmO2nbs9Fe96N9E',
    appId: '1:714082287468:ios:243e2a46cc00560a57bd49',
    messagingSenderId: '714082287468',
    projectId: 'jewel-assist-e3d9c',
    storageBucket: 'jewel-assist-e3d9c.appspot.com',
    iosBundleId: 'com.example.jewelAssist',
  );
}
